using System.ComponentModel;

namespace Karate.SqLite.Services.enumeration
{

	internal enum ScriptItems
	{
		[Description("Class.InsertClass.sql")]
		InsertClass,
		[Description("Class.DeleteClass.sql")]
		DeleteClass,
		[Description("Class.GetClasses.sql")]
		GetClasses,
		[Description("Member.GetAllMembers.sql")]
		GetAllMembers,
		[Description("Member.GetActiveMembers.sql")]
		GetActiveMembers,
		[Description("Stats.GetStatistics.sql")]
		GetStatistics,
		[Description("Badge.InsertBadge.sql")]
		InsertBadge,
		[Description("Badge.GetBadges.sql")]
		GetBadges,
		[Description("Badge.DeleteBadge.sql")]
		DeleteBadge,
		[Description("Style.GetStyles.sql")]
		GetStyles,
		[Description("Style.InsertStyle.sql")]
		InsertStyle,
		[Description("Style.DeleteStyle.sql")]
		DeleteStyle,
		[Description("Grade.GetGradesByStyle.sql")]
		GetGradesByStyle,
		[Description("Grade.InsertGrade.sql")]
		InsertGrade,
		[Description("Grade.DeleteGrade.sql")]
		DeleteGrade,
		[Description("Member.GetMemberById.sql")]
		GetMemberById,
		[Description("Address.GetAddressById.sql")]
		GetAddressById,
		[Description("Address.GetAddresses.sql")]
		GetAddresses,
		[Description("Address.InsertAddress.sql")]
		InsertAddress,
		[Description("Licence.GetLicenceByMemberId.sql")]
		GetLicenceByMemberId,
		[Description("Member.UpdateMember.sql")]
		UpdateMember,
		[Description("Member.InsertMember.sql")]
		InsertMember,
		[Description("Address.UpdateAddress.sql")]
		UpdateAddress,
		[Description("Member.InaeactiveMember.sql")]
		InactiveMember,
		[Description("Licence.InsertLicence.sql")]
		InsertLicense,
		[Description("Grade.InsertMemberGrading.sql")]
		InsertMemberGrading,
		[Description("Grade.GetGradesByMemberId.sql")]
		GetGradesByMemberId,
		[Description("License.UpdateLicense.sql")]
		UpdateLicense,
		[Description("Member.GetInactiveMembers.sql")]
		GetInactiveMembers,
		[Description("Badge.GetBadgesByMemberId.sql")]
		GetBadgesByMemberId,
		[Description("Member.ReactiveMember.sql")]
		ReactiveMember,
		[Description("Grade.DeleteMemberGrading.sql")]
		DeleteMemberGrading,
		[Description("Member.InsertMemberBadge.sql")]
		InsertMemberBadge
	}
}
